global:
  scrape_interval: "10s" # scrape targets every 10 seconds

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  - job_name: 'api-backend'
    static_configs:
      - targets: ['host.docker.internal:5328']