global:
  scrape_interval: "10s"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']

  - job_name: 'api-service'
    static_configs:
      - targets: ['localhost:5328']
 
  - job_name: 'node resources'
    static_configs:
      - targets: ['node_exporter:9100']
    params:
      collect[]:
        - cpu
        - meminfo
        - diskstats
        - netdev
        - netstat

  - job_name: 'node storage'
    static_configs:
      - targets: ['node_exporter:9100']
    params:
      collect[]:
        - filefd
        - filesystem
        - xfs
