import AuthProvider from "@/contexts/AuthContext";
import "../styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const bodyStyle = {
    backgroundColor: '#1D2125',
  };

  return (
    <html lang="en">
      <body className={inter.className} style={bodyStyle}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
